spring.application.name=taco-cloud
spring.datasource.username=postgres
spring.datasource.password=1245780
spring.datasource.url=spring.datasource.url=jdbc:postgresql://localhost:5432/taco_cloud_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.security.oauth2.client.registration.facebook.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.facebook.scope[0]=email
spring.security.oauth2.client.registration.facebook.scope[1]=public_profile
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.base-path=/data-api




