spring.application.name=taco-cloud
spring.datasource.username=postgres
spring.datasource.password=1245780
spring.datasource.url=jdbc:postgresql://localhost:5432/taco_cloud_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.base-path=/data-api
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks




