spring.application.name=taco-cloud
spring.datasource.username=postgres
spring.datasource.password=1245780
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.oauth2.client.registration.facebook.client-id=<facebook client id>
spring.security.oauth2.client.registration.facebook.client-secret=<faceboo client secret>
spring.security.oauth2.client.registration.facebook.scope[2]=email, public_profile




